### ISSUE TITLE
[FeatureRequest] Disable disconnectAll

### ISSUE THREAD

**Issue by minitoine** [Lusito/typed-signals#13]
Hello :)

I'm writing a library exporting objects that can emit signals.
These signals are also used internally by the library, and so there is a risk that disconnectAll is called on some signals.

Would it be possible to add an option to to Signal constructor to disable the disconnectAll method ?
For example, we could exist the function or throwing an error.

Thanks

**Comment by Lusito** [comment]
Sounds like a reasonable request. Let me think about how to solve this nicely.
