### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by supermoos** [Lusito/typed-signals#2]
Seems like a solid lib, I have one request though. Would it be possible to add a `disconnect(callback:CB)` function on a `Signal`, instead of only having `disconnectAll()`. I would like not having to store references to signalconnections  in order to break a single connection, the current implementation doesn't seem to support this?

**Comment by supermoos** [comment]
Amazing, that was fast! Thank you!

**Comment by Lusito** [comment]
I've added a new version that contains a disconnect() callback. Documentation will update soon.

**Comment by Lusito** [comment]
See https://lusito.github.io/typed-signals/classes/_signal_.signal.html#disconnect
