### ISSUE TITLE
Check Signal Connections

### ISSUE THREAD

**Issue by b12-144** [Lusito/typed-signals#8]
Hi, this library is awesome!
Is it possible to check if a Signal has connections and connections count attached to it without using SignalConnections? 
Ex:
```typescript
let mySignal = new Signal<() => void>();
mySignal.connect(()=>console.log('first'));
mySignal.connect(()=>console.log('second'));

//Something like this
mySignal.hasConnections()//would print true
mySignal.connectionsCount()//2
```

Thank you!

**Comment by Lusito** [comment]
Hi, thanks for the feedback. I've added this in Version 2.4.0
